spring.application.name=Attendance_System_UoK

spring.data.mongodb.uri=mongodb+srv://prasannadilshan2002_db_user:7dpqhFFA7bOcbPCF@cluster0.g5fhffw.mongodb.net/Attendance_system?retryWrites=true&w=majority&appName=Cluster0



# JWT Configuration
jwt.secret=mySecretKeyThatIsAtLeast32CharactersLongForHS256Algorithm
jwt.expiration=86400000

# Server Configuration
server.address=0.0.0.0
server.port=8080

# Logging
logging.level.com.example.Attendance_System_UoK=DEBUG
logging.level.org.springframework.security=DEBUG

# Error Handling
server.error.include-message=always
server.error.include-binding-errors=always

# Mail Configuration
# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=prasannadilshan2002@gmail.com
spring.mail.password=mlzp buyi bneo samj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.ssl.trust=*
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.connectiontimeout=30000
spring.mail.properties.mail.smtp.timeout=30000
spring.mail.properties.mail.smtp.writetimeout=30000
